config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customer, skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :customer do
    #リダイレクト用にgetメソッドによるログアウトを追加
    get '/customer/sign_out', to: 'public/sessions#withdraw_destroy', as: :customer_log_out
  end

  scope module: :public do
    #public/homes
    root to: 'homes#top'
    get 'about' => 'homes#about'

    #public/mypage
    get 'my_page/withdraw_confirm' => 'my_pages#withdraw_confirm'
    patch 'my_page/withdraw' => 'my_pages#withdraw'
    resource :my_page, only: [:show, :edit, :update]

    #public/items
    get 'items/genre/:id' => "items#genre", as: "items_genre"
    get 'items/search' => "items#search"
    resources :items, only: [:index, :show]

    #public/cart_items
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    #public/orders
    post 'orders/confirm', as: "orders_confirm"
    get 'orders/thanks', as: "orders_thanks"
    resources :orders, only: [:new, :index, :show, :create]

    #public/addresses
    resources :addresses, only: [:index, :edit, :update, :destroy, :create]

    #devise
  end

  namespace :admin do
    #admin/items
    get 'items/search' => "items#search"
    resources :items, except: [:destroy]
    
    #admin/orders
    root to: "orders#index"
    resources :orders, only: [:index, :show, :update]
    
    #admin/customers
    get "customers/:id/orders" => "customers#orders", as: "customer_orders"
    resources :customers, only: [:index, :edit, :show, :update]
    
    #admin/genres
    resources :genres, only: [:index, :edit, :create, :update]
    
    #admin/order_items
    patch "order_items/:id" => "order_items#update", as: "order_item"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  belongs_to :genre
  has_many :cart_items
  has_many :order_items

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
  validates :is_active, inclusion: [true, false]
  validates :image, presence: true

  def tax_rate
    1.1
  end

  def tax_included_price
    (price * tax_rate).floor
  end

  def get_image(w, h)
    image.variant(resize_to_limit: [w, h]).processed
  end

  def status_color(active)
    active ? "text-success" : "text-muted"
  end

  def status
    get_status_string(is_active)
  end

  def get_status_string(active)
    active ? "販売中" : "販売停止中"
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item), notice: "商品を正常に追加しました。"
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item), notice: "商品を正常に保存しました。"
    else
      render :edit
    end
  end

  def index
    set_items(Item.all)
    @title = "商品一覧"
  end

  def search
    word = params[:search_word]
    searched = Item.where("name like ?", "%#{word}%")
    @title = "検索結果: " + word
    set_items(searched)
    render :index
  end

  def show
    @item = Item.find(params[:id])
  end

  private
  def set_items(source)
    @items_count = source.size
    @items = Kaminari.paginate_array(source).page(params[:page]).per(10)
  end
  def item_params
    params.require(:item).permit(:name, :introduction, :image, :price, :is_active, :genre_id)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<div class="row my-2">
  <%= f.label :image, "商品画像", class: "col-3" %>
  <%= f.file_field :image, class: "form-control col-8" %>
</div>

<div class="row my-2">
  <%= f.label :name, "商品名" , class: "col-3" %>
  <%= f.text_field :name, placeholder: "商品名", class: "form-control col-8" %>
</div>

<div class="row my-2">
  <%= f.label :introduction, "商品説明", class: "col-3" %>
  <%= f.text_area :introduction, placeholder: "ここに説明文を記入します", class: "form-control col-8" %>
</div>

<div class="row my-2">
  <%= f.label :genre_id, "ジャンル", class: "col-3" %>
  <%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :name), {}, class: "form-control col-8" %>
</div>

<div class="row my-2">
  <%= f.label :price, "税抜価格", class: "col-3" %>
  <%= f.text_field :price, placeholder: "1000", class: "form-control col-8" %>円
</div>

<div class="row  my-2form-group">
  <%= f.label :is_active, "販売ステータス", class: "col-3" %>
  <% [true, false].each do |st| %>
    <div class="form-check form-check-inline">
      <%= f.radio_button :is_active, st, class: "form-check-input" %>
      <%= f.label :is_active, @item.get_status_string(st), class: "form-check-label" %>
    </div>
  <% end %>
</div>

app/views/admin/items/_status.html.erb
<span class="<%= item.status_color(item.is_active) %>"><b><%= item.status %></b></span>

app/views/admin/items/edit.html.erb
<%= render "layouts/section", title: "商品編集" %>
<%= form_with model: @item, url: admin_item_path(@item), method: :patch, local: true do |f| %>
  <%= render "layouts/error_messages", resource: @item %>
  <%= render "form", f: f %>
  <%= f.submit "変更を保存", class: "btn btn-success d-block mx-auto" %>
<% end %>

app/views/admin/items/index.html.erb
<div class="row">
<%= render "layouts/section", title: (@title + "(全#{@items_count}件)") %>
<%= link_to "+", new_admin_item_path, class: "btn text-secondary rounded-circle shadow-sm btn-light m-4 ml-auto" %>
</div>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>商品ID</th>
      <th>商品名</th>
      <th>税抜き価格</th>
      <th>ジャンル</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |i| %>
    <tr>
      <td><%= i.id %></td>
      <td><u><%= link_to i.name, admin_item_path(i), class: "text-dark" %></u></td>
      <td><%= i.price.to_s(:delimited) %></td>
      <td><%= i.genre.name %></td>
      <td><%= render "status", item: i %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @items %>

app/views/admin/items/new.html.erb
<%= render "layouts/section", title: "商品新規登録" %>
<%= form_with model: @item, url: admin_items_path, method: :post, local: true do |f| %>
  <%= render "layouts/error_messages", resource: @item %>
  <%= render "form", f: f %>
  <%= f.submit "新規登録", class: "btn btn-success d-block mx-auto" %>
<% end %>

app/views/admin/items/show.html.erb
<%= render "layouts/section", title: "商品詳細" %>
<div class="row">
  <div "m-3">
    <%= image_tag @item.get_image(300, 200) %>
  </div>
  <div>
    <table class="table m-3 table-borderless">
      <tbody>
        <tr>
          <td>商品名</td>
          <td><%= @item.name %></td>
        </tr>
        <tr>
          <td>商品説明</td>
          <td><%= @item.introduction %></td>
        </tr>
        <tr>
          <td>ジャンル</td>
          <td><%= @item.genre.name %></td>
        </tr>
        <tr>
          <td>税込価格(税抜価格)</td>
        <td><%= "#{@item.tax_included_price.to_s(:delimited)}(#{@item.price.to_s(:delimited)}) 円" %></td>
        </tr>
        <tr>
          <td>ステータス</td>
          <td><%= render "status", item: @item %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="col-12 text-center">
    <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
  </div>
</div>