config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customer, skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :customer do
    #リダイレクト用にgetメソッドによるログアウトを追加
    get '/customer/sign_out', to: 'public/sessions#withdraw_destroy', as: :customer_log_out
  end

  scope module: :public do
    #public/homes
    root to: 'homes#top'
    get 'about' => 'homes#about'

    #public/mypage
    get 'my_page/withdraw_confirm' => 'my_pages#withdraw_confirm'
    patch 'my_page/withdraw' => 'my_pages#withdraw'
    resource :my_page, only: [:show, :edit, :update]

    #public/items
    get 'items/genre/:id' => "items#genre", as: "items_genre"
    get 'items/search' => "items#search"
    resources :items, only: [:index, :show]

    #public/cart_items
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    #public/orders
    post 'orders/confirm', as: "orders_confirm"
    get 'orders/thanks', as: "orders_thanks"
    resources :orders, only: [:new, :index, :show, :create]

    #public/addresses
    resources :addresses, only: [:index, :edit, :update, :destroy, :create]

    #devise
  end

  namespace :admin do
    #admin/items
    get 'items/search' => "items#search"
    resources :items, except: [:destroy]
    
    #admin/orders
    root to: "orders#index"
    resources :orders, only: [:index, :show, :update]
    
    #admin/customers
    get "customers/:id/orders" => "customers#orders", as: "customer_orders"
    resources :customers, only: [:index, :edit, :show, :update]
    
    #admin/genres
    resources :genres, only: [:index, :edit, :create, :update]
    
    #admin/order_items
    patch "order_items/:id" => "order_items#update", as: "order_item"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  has_many :addresses

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true

  def cart_total
    cart_items.sum{|ci| ci.subtotal }
  end

  def order_items
    cart_items.map{|ci| ci.to_order_item }
  end

  def destroy_all_cart
    cart_items.each{|ci| ci.destroy }
  end

  def address_display(with_name)
    "〒#{postal_code} #{address}" + (with_name ? " #{name}" : "")
  end

  def full_name
    last_name + first_name
  end

  def get_status_color(active)
    active ? "text-success" : "text-muted"
  end

  def status
    get_status_string(is_active)
  end

  def get_status_string(active)
    active ? "有効" : "退会"
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer), notice: "会員情報を正常に保存しました。"
    else
      render :edit
    end
  end

  def orders
    @customer = Customer.find(params[:id])
    @orders = @customer.orders.page(params[:page])
  end

  protected
  def customer_params
    params.require(:customer).permit(:first_name, :last_name, :first_name_kana, :last_name_kana,
      :email, :postal_code, :address, :telephone_number, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/_form.html.erb
  <div class="field row form-inline m-2">
    <div class="col-3">氏名</div>
    <%= f.text_field :last_name, autofocus: true, placeholder: "長野", class: "form-control mr-3" %>
    <%= f.text_field :first_name, placeholder: "惠喜", class: "form-control" %>
  </div>
  <div class="field row form-inline m-2">
    <div class="col-3">フリガナ</div>
    <%= f.text_field :last_name_kana, placeholder: "ナガノ", class: "form-control mr-3" %>
    <%= f.text_field :first_name_kana, placeholder: "ケイキ", class: "form-control" %>
  </div>

  <div class="field row form-inline m-2">
    <%= f.label :postal_code, "郵便番号(ハイフンなし)", class: "col-3 justify-content-start" %>
    <%= f.text_field :postal_code, placeholder: "1234567", class: "form-control" %>
  </div>

  <div class="field row form-inline m-2">
    <%= f.label :address, "住所", class: "col-3 justify-content-start" %>
    <%= f.text_field :address, placeholder: "東京都千代田区千代田1-1", class: "form-control col-6" %>
  </div>

  <div class="field row form-inline m-2">
    <%= f.label :telephone_number, "電話番号(ハイフンなし)", class: "col-3  justify-content-start" %>
    <%= f.text_field :telephone_number, placeholder: "09012345678", class: "form-control" %>
  </div>

  <div class="field row form-inline m-2">
    <%= f.label :email, "メールアドレス", class: "col-3 justify-content-start" %>
    <%= f.email_field :email, placeholder: "mail@example.com", class: "form-control" %>
  </div>

app/views/admin/customers/_status.html.erb
<span class="<%= customer.get_status_color(customer.is_active) %>"><b><%= customer.status %></b></span>

app/views/admin/customers/edit.html.erb
<%= render "layouts/section", title: @customer.full_name + "さんの会員情報編集" %>
<%= render "layouts/error_messages", resource: @customer %>
<%= form_with(model:@customer, url: admin_customer_path(@customer), method: :patch, local: true) do |f| %>

  <div class="field row m-2">
    <div class="col-3">会員ID</div>
    <div class="col-9"><%= @customer.id %></div>
  </div>
  <%= render "form", f: f %>
  <div class="field row form-inline m-2">
    <%= f.label :is_active, "会員ステータス", class: "col-3 justify-content-start" %>
    <div class="form-check">
    <% [true, false].each do |st| %>
      <%= f.radio_button :is_active, st, class: "form-check-input" %>
      <%= f.label :is_active, @customer.get_status_string(st), class: "form-check-label mr-3" %>
    <% end %>
    </div>
  </div>

  <div class="actions text-center my-4">
    <%= f.submit "変更を保存", class: "btn btn-success" %>
  </div>
<% end %>

app/views/admin/customers/index.html.erb
<%= render "layouts/section", title: "会員一覧" %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>会員ID</th>
      <th>氏名</th>
      <th>メールアドレス</th>
      <th>ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% @customers.each do |c| %>
    <tr>
      <td><%= c.id %></td>
      <td><u><%= link_to c.full_name, admin_customer_path(c), class: "text-dark" %></u></td>
      <td><%= c.email %></td>
      <td><%= render "status", customer: c %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @customers %>

app/views/admin/customers/orders.html.erb
<%= render "admin/orders/list", title: "#{@customer.full_name}さんの注文履歴", orders: @orders, show_customer: false %>

app/views/admin/customers/show.html.erb
<%= render "layouts/section", title: @customer.full_name + "さんの会員詳細" %>
<table class="table table-borderless">
  <tbody>
    <tr>
      <td>会員ID</td>
      <td><%= @customer.id %></td>
    </tr>
    <tr>
      <td>氏名</td>
      <td><%= @customer.last_name %> <%= @customer.first_name %></td>
    </tr>
    <tr>
      <td>フリガナ</td>
      <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
    </tr>
    <tr>
      <td>郵便番号</td>
      <td><%= @customer.postal_code %></td>
    </tr>
    <tr>
      <td>住所</td>
      <td><%= @customer.address %></td>
    </tr>
    <tr>
      <td>電話番号</td>
      <td><%= @customer.telephone_number %></td>
    </tr>
    <tr>
      <td>メールアドレス</td>
      <td><%= @customer.email %></td>
    </tr>
    <tr>
      <td>会員ステータス</td>
      <td><%= render "status", customer: @customer %></td>
    </tr>
  </tbody>
</table>
<div class="text-center">
  <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success mr-3" %>
  <%= link_to "注文履歴一覧を見る", admin_customer_orders_path(@customer), class: "btn btn-primary" %>
</div>