config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customer, skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :customer do
    #リダイレクト用にgetメソッドによるログアウトを追加
    get '/customer/sign_out', to: 'public/sessions#withdraw_destroy', as: :customer_log_out
  end

  scope module: :public do
    #public/homes
    root to: 'homes#top'
    get 'about' => 'homes#about'

    #public/mypage
    get 'my_page/withdraw_confirm' => 'my_pages#withdraw_confirm'
    patch 'my_page/withdraw' => 'my_pages#withdraw'
    resource :my_page, only: [:show, :edit, :update]

    #public/items
    get 'items/genre/:id' => "items#genre", as: "items_genre"
    get 'items/search' => "items#search"
    resources :items, only: [:index, :show]

    #public/cart_items
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    #public/orders
    post 'orders/confirm', as: "orders_confirm"
    get 'orders/thanks', as: "orders_thanks"
    resources :orders, only: [:new, :index, :show, :create]

    #public/addresses
    resources :addresses, only: [:index, :edit, :update, :destroy, :create]

    #devise
  end

  namespace :admin do
    #admin/items
    get 'items/search' => "items#search"
    resources :items, except: [:destroy]
    
    #admin/orders
    root to: "orders#index"
    resources :orders, only: [:index, :show, :update]
    
    #admin/customers
    get "customers/:id/orders" => "customers#orders", as: "customer_orders"
    resources :customers, only: [:index, :edit, :show, :update]
    
    #admin/genres
    resources :genres, only: [:index, :edit, :create, :update]
    
    #admin/order_items
    patch "order_items/:id" => "order_items#update", as: "order_item"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_items

  attribute :order_status, :integer, default: 0
  attribute :payment_method, :integer, default: 0

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { wait_for_deposit: 0, confirmed_deposit: 1, in_production: 2, in_packing: 3, shipped: 4 }

  validates :name, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :postage, presence: true
  validates :total_fee, presence: true
  validates :payment_method, presence: true

  def production_order_status
    ois = order_items.map{|oi| OrderItem.production_statuses[oi.production_status] }
    return 1 if ois.max <= 1
    return 3 if ois.min >= 3
    return 2
  end

  def valid_status_nums
    os_num = Order.order_statuses[order_status]
    return [0, 1] if os_num == 0
    case production_order_status
    when 1
      return [0, 1]
    when 2
      return [2]
    when 3
      return [3, 4]
    end
  end

  def valid_status
    valid_status_nums.map{|vn| Order.order_statuses.key(vn) }
  end

  def now_postage
    800
  end

  def address_valid?
    @address.present? && @postal_code.present? && @name.present?
  end

  def address_display(with_name)
    "〒#{postal_code} #{address}" + (with_name ? " #{name}" : "")
  end

  def payment
    get_payment_str(payment_method)
  end
  def get_payment_str(param)
    Order.payment_methods_i18n[param]
  end

  def od_status
    get_order_status(order_status)
  end
  def get_order_status(param)
    Order.order_statuses_i18n[param]
  end

  def amount
    order_items.map{|i| i.amount}.sum
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @orders = Order.all.order(created_at: "DESC").page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(admin_order_params)
    if @order.order_status != "wait_for_deposit"
      @order.order_items.each do |oi|
        if oi.production_status == "disabled"
          oi.update(production_status: "wait_for_production")
        end
      end
    end
    redirect_to admin_order_path(@order), notice: "注文ステータスを正常に更新しました。"
  end

  private
  def admin_order_params
    params.require(:order).permit(:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/_list.html.erb
<%= render "layouts/section", title: title %>
<table class="table">
  <thead class="thead-light">
    <tr>
      <th>購入日時</th>
      <% if show_customer %>
      <th>購入者</th>
      <% end %>
      <th>注文個数</th>
      <th>注文ステータス</th>
    </tr>
  </thead>
  <tbody>
    <% orders.each do |od| %>
    <tr>
      <td><u><%= link_to od.created_at.strftime('%Y/%m/%d %T'), admin_order_path(od), class:"text-dark underline" %></u></td>
      <% if show_customer %>
      <td><%= od.customer.full_name %></td>
      <% end %>
      <td><%= od.amount %></td>
      <td><%= od.od_status %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<%= paginate orders %>

app/views/admin/orders/index.html.erb
<%= render "list", title: "注文履歴一覧", orders: @orders, show_customer: true %>

app/views/admin/orders/show.html.erb
<%= render "layouts/section", title: "注文履歴詳細" %>
<table class="table table-borderless">
  <tbody>
    <tr>
      <th>購入者</th>
      <td><u><%= link_to @order.customer.full_name, admin_customer_path(@order.customer), class: "text-dark" %></u></td>
    </tr>
    <tr>
      <th>注文日</th>
      <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
    </tr>
    <tr>
      <th>配送先</th>
      <td>
        <%= @order.address_display(false) %><br>
        <%= @order.name %>
      </td>
    </tr>
    <tr>
      <th>支払方法</th>
      <td><%= @order.payment %></td>
    </tr>
    <tr>
      <th>注文ステータス</th>
      <td>
      <%= form_with model: @order, url: admin_order_path(@order), method: :patch,
        class: "form-inline" do |f| %>
        <%= f.select :order_status, @order.valid_status.map{|s|
          [Order.order_statuses_i18n[s], s]
        }, {}, class: "form-control" %>
        <%= f.submit "更新", class: "btn btn-success ml-3" %>
      <% end %>
      </td>
    </tr>
  </tbody>
</table>
<div class="row">
  <table class="table col-9">
    <thead class="thead-light">
      <tr>
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>制作ステータス</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @order.order_items.each do |oi| %>
      <tr>
        <td><%= oi.item.name %></td>
        <td><%= oi.tax_included_price.to_s(:delimited) %></td>
        <td><%= oi.amount %></td>
        <td><%= oi.subtotal.to_s(:delimited) %></td>
        <td>
          <%= form_with model: oi, url: admin_order_item_path(oi), method: :patch,
            class: "form-inline" do |f| %>
            <%= f.select :production_status, oi.valid_status.map{|s|
              [OrderItem.production_statuses_i18n[s], s]
            }, {}, class: "form-control" %>
            <%= f.submit "更新", class: "btn btn-success ml-3" %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <table class="table table-sm table-borderless col-3 mt-auto">
    <tbody>
      <tr>
        <th>商品合計</th>
        <td><%= @order.order_items.sum{|oi| oi.subtotal }.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th>送料</th>
        <td><%= @order.postage.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <th>請求金額合計</th>
        <td><b><%= @order.total_fee.to_s(:delimited) %>円</b></td>
      </tr>
    </tbody>
  </table>
</div>