config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customer, skip:[:passwords], controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  devise_scope :customer do
    #リダイレクト用にgetメソッドによるログアウトを追加
    get '/customer/sign_out', to: 'public/sessions#withdraw_destroy', as: :customer_log_out
  end

  scope module: :public do
    #public/homes
    root to: 'homes#top'
    get 'about' => 'homes#about'

    #public/mypage
    get 'my_page/withdraw_confirm' => 'my_pages#withdraw_confirm'
    patch 'my_page/withdraw' => 'my_pages#withdraw'
    resource :my_page, only: [:show, :edit, :update]

    #public/items
    get 'items/genre/:id' => "items#genre", as: "items_genre"
    get 'items/search' => "items#search"
    resources :items, only: [:index, :show]

    #public/cart_items
    delete 'cart_items/destroy_all'
    resources :cart_items, only: [:index, :create, :update, :destroy]

    #public/orders
    post 'orders/confirm', as: "orders_confirm"
    get 'orders/thanks', as: "orders_thanks"
    resources :orders, only: [:new, :index, :show, :create]

    #public/addresses
    resources :addresses, only: [:index, :edit, :update, :destroy, :create]

    #devise
  end

  namespace :admin do
    #admin/items
    get 'items/search' => "items#search"
    resources :items, except: [:destroy]
    
    #admin/orders
    root to: "orders#index"
    resources :orders, only: [:index, :show, :update]
    
    #admin/customers
    get "customers/:id/orders" => "customers#orders", as: "customer_orders"
    resources :customers, only: [:index, :edit, :show, :update]
    
    #admin/genres
    resources :genres, only: [:index, :edit, :create, :update]
    
    #admin/order_items
    patch "order_items/:id" => "order_items#update", as: "order_item"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger" id="error_explanation">
    <b>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </b>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_section.html.erb
<h5 class="m-4 px-2 py-1 d-inline-block alert-secondary text-center"><%= title %></h5>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="row bg-light border-bottom sticky-top">
      <div class="col-2 my-auto ml-3">
        <%= link_to (admin_signed_in? ? admin_root_path : root_path), class: "text-success" do %>
          <%= image_tag 'logo.png', size: "220x110" %>
        <% end %>
      </div>
      <div class="col-4 text-right my-auto mr-3">
        <%= customer_signed_in? ? "ようこそ、#{current_customer.last_name} さん" : nil %>
      </div>
      <div class="col-5 row">
        <nav class="navbar col-12">
          <% if admin_signed_in? %>
            <div class="nav-item m-1"><%= link_to "商品一覧", admin_items_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "会員一覧", admin_customers_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "注文履歴一覧", admin_orders_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "ジャンル一覧", admin_genres_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class:"btn btn-outline-secondary"  %></div>
          <% elsif customer_signed_in? %>
            <div class="nav-item m-1"><%= link_to "マイページ", my_page_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "商品一覧", items_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "カート", cart_items_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class:"btn btn-outline-secondary" %></div>
          <% else %>
            <div class="nav-item m-1"><%= link_to "About", about_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "商品一覧", items_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "新規登録", new_customer_registration_path, class:"btn btn-outline-secondary" %></div>
            <div class="nav-item m-1"><%= link_to "ログイン", new_customer_session_path, class:"btn btn-outline-secondary" %></div>
          <% end %>
        </nav>
        <div class="ml-auto row form-inline mb-1">
          <%= form_with url: (admin_signed_in? ? admin_items_search_path : items_search_path),
            method: :get, local: true, class:"ml-auto" do |f| %>
            <%= f.text_field :search_word, placeholder: "商品名で検索", class: "form-control mr-0" %>
            <%= f.submit "検索", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </header>
    <main class="container py-2">
      <% if flash.now[:alert] %>
        <p class="alert alert-danger my-2"><%= flash.now[:alert] %></p>
      <% end %>
      <% if flash.now[:notice] %>
        <p class="alert alert-success my-2"><%= flash.now[:notice] %></p>
      <% end %>
      <%= yield %>
    </main>
    <footer class="fixed-bottom">
      <div class="mt-3 py-4 text-secondary bg-light border-top text-center">
        ©Copyright NaganoCake, Co., Ltd.
      </div>
    </footer>
  </body>
</html>